### ISSUE TITLE
Include question about testing frameworks

### ISSUE THREAD

**Issue by flub** [python/python-dev-survey#3]
As one of the maintainers of [pytest](https://github.com/pytest-dev/pytest) I would be very interested in seeing a question about the use of testing frameworks included the next time the survey runs.

**Comment by filippovd20** [comment]
I think it's a great suggestion! Makes sense to have a question on testing frameworks since unit testing is the core part of any type of development.

**Comment by flub** [comment]
I believe this was included in the latter surveys, thanks!
